In [13]:
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: yfinance in /usr/local/lib/python3.7/dist-packages (0.1.74)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.9.1)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.28.1)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2022.6.15)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.1.0)

In [14]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings("ignore")
import yfinance as yf
yf.pdr_override()

In [15]:
symbol = 'AAPL'
start = '2021-08-20'
end = '2022-08-20'
df = yf.download(symbol, start, end)
df = df.reset_index()
df.head()

[*********************100%***********************]  1 of 1 completed

,Date,Open,High,Low,Close,Adj Close,Volume
0,2021-08-20,147.440002,148.500000,146.779999,148.190002,147.364243,60549600
1,2021-08-23,148.309998,150.190002,147.889999,149.710007,148.875778,60131800
2,2021-08-24,149.449997,150.860001,149.149994,149.619995,148.786255,48606400
3,2021-08-25,149.809998,150.320007,147.800003,148.360001,147.533279,58991300
4,2021-08-26,148.350006,149.119995,147.509995,147.539993,146.717865,48597200

In [16]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
247,2022-08-15,171.520004,173.389999,171.350006,173.190002,173.190002,54091700
248,2022-08-16,172.779999,173.710007,171.660004,173.029999,173.029999,56377100
249,2022-08-17,172.770004,176.149994,172.570007,174.550003,174.550003,79542000
250,2022-08-18,173.750000,174.899994,173.119995,174.149994,174.149994,62290100
251,2022-08-19,173.029999,173.740005,171.309998,171.520004,171.520004,70211500

In [17]:
X_train = df[df.columns[1:5]] 
Y_train = df['Adj Close']

In [18]:
X_train = X_train.values[:-1]
Y_train = Y_train.values[1:]

In [19]:
lr = LinearRegression()

In [20]:
lr.fit(X_train, Y_train)

LinearRegression()

In [21]:
X_test = df[df.columns[1:5]].values[:-1]
Y_test = df['Adj Close'].values[1:]

In [22]:
lr.score(X_test, Y_test)

0.944432148873301

In [23]:
opening_price = float(input('Open: '))
high = float(input('High: '))
low = float(input('Low: '))
close = float(input('Close: '))
print('My Prediction the opening price will be:', lr.predict([[opening_price, high, low, close]])[0])

Open: 173.029999
High: 173.740005
Low: 171.309998
Close: 171.520004
My Prediction the opening price will be: 170.63998416180655